# Generated by Django 4.2.16 on 2024-11-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='is_first_video',
            field=models.BooleanField(default=False),
        ),
    ]
